# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "Nomalah"
    schedule:
      interval: "weekly"
    groups:
      capacitor:
        patterns:
          - "@capacitor/core"
          - "@capacitor/android"
          - "@capacitor/ios"
          - "@capacitor/cli"
      capacitor-plugins:
        patterns:
          - "@capacitor/*"
          - "@capacitor-community/*"
        exclude-patterns:
          - "@capacitor/core"
          - "@capacitor/android"
          - "@capacitor/ios"
          - "@capacitor/cli"
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "Nomalah"
    schedule:
      interval: "weekly"
