name: Build and Deploy Development Branch
on:
  push:
    branches: [ staging ]
    paths-ignore:
      - '.github/workflows/**'
      - 'ios/**'
      - 'android/**'
      - '.vscode/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'build'
      
      - name: Build
        run: |
          cd build
          echo "VITE_BASE_URL=/acchymns-dev/" > .env # We deploy to github.io/acchyms-dev, which we serve on the root
          npm i
          npm run build
          npx cap copy web # This runs our helper script to compress the song book info
          cd ..
      
      - name: Checkout Dev Target
        uses: actions/checkout@v3
        with:
          repository: ACC-Hymns/acchymns-dev
          path: 'deploy'
          token: ${{ secrets.DEPLOYMENT_PAT }}
      
      - name: Push files to target
        run: |
          rm -r deploy/*
          cp -r build/* deploy
          cd deploy
          cp deploy/index.html deploy/404.html # This is to avoid 404 errors on reload (Ugly fix but okay I guess)
          touch .nojekyll
          git add .
          git commit -m $GITHUB_SHA
          git push
